### ISSUE TITLE
pom.xml build member

### ISSUE THREAD

**Issue by mordex007** [random-maven/flatten-maven-plugin#6]
Is there an option (or specific set of configs) to include build member with childs pluginManagement and plugins (and to add only those, defined in current pom.xml) during flatten action?
I need this option because of the maven multimodule configuration. This can be achieved by flatten-maven-plugin from mojohaus but has other disadvantages.

**Comment by Andrei-Pozolotin** [comment]
1. the semantics of `random-maven/flatten-maven-plugin` is to remove only, not to add
2. of course, both parent and child entries can be removed
3. if parent and child removal must be different, that can be controlled by profiles
