### ISSUE TITLE
Any change to join forces with mojohaus again?

### ISSUE THREAD

**Issue by hohwille** [random-maven/flatten-maven-plugin#7]
* https://github.com/mojohaus/flatten-maven-plugin/issues/64
* https://github.com/mojohaus/flatten-maven-plugin/issues/58
* https://github.com/mojohaus/flatten-maven-plugin/issues/59
* https://github.com/mojohaus/flatten-maven-plugin/issues/60
* https://github.com/mojohaus/flatten-maven-plugin/issues/56

As you were complaining about missing feedback and reaction on my side, it would be very kind if you could give feedback. 

Thanks in advance. Jörg

**Comment by Andrei-Pozolotin** [comment]
Jörg: Sorry no. No bandwidth for that. Thank you, Andrei
