### ISSUE TITLE
Optional dependencies lose their optionalness

### ISSUE THREAD

**Issue by diamondq** [random-maven/flatten-maven-plugin#8]
A dependency with an `<optional>true</optional>` set, loses this flag when copied over to the flattened pom. This seems like a simple fix in Support.resolveApplyDeclared (ie. dependency.setOptional(artifact.isOptional)); ).

EDIT: Turns out that the scenario only occurs if the dependency is NOT present in the local POM's <dependencies> section. For example, within a profile or a parent. If it's in the local POM, the existing code works fine.

Cheers

**Comment by Andrei-Pozolotin** [comment]
please PR

**Comment by Andrei-Pozolotin** [comment]
1. thank you for PR, released:
https://search.maven.org/artifact/com.carrotgarden.maven/flatten-maven-plugin

2. please confirm v 1.7.x works for you
https://github.com/random-maven/flatten-maven-plugin/releases

**Comment by diamondq** [comment]
Seems to be working great. Thanks
